### ISSUE TITLE
Gd only handles true color images and have problems with transparency

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-express#209]

**Comment by rosell-dk** [comment]
This is about to be fixed in webp-convert...

**Comment by rosell-dk** [comment]
Fixed in a new release of webp-convert (1.3.4). A `composer update` will pull it in.

**Comment by jonathanernst** [comment]
@rosell-dk We still have this issue with latest webp-express (webp-convert 1.3.9).

See : https://ticketack.com/github_webp-express_issue_209/logo_ticketack-1.png vs https://ticketack.com/github_webp-express_issue_209/logo_ticketack-1.gd.webp (gd) vs https://ticketack.com/github_webp-express_issue_209/logo_ticketack-1.cwebp.webp (cwebp)

Thanks
